In [1]:
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["A", "B", "C", "D"],
    "city": ["Bangalore", "Delhi", "Mumbai", "Chennai"]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "customer_id": [1, 2, 1, 3, 5],
    "amount": [500, 700, 300, 400, 600]
})

In [8]:
orders

   order_id  customer_id  amount
0       101            1     500
1       102            2     700
2       103            1     300
3       104            3     400
4       105            5     600

In [9]:
customers

   customer_id name       city
0            1    A  Bangalore
1            2    B      Delhi
2            3    C     Mumbai
3            4    D    Chennai